version: '3.8'

services:

  jenkins-master:
    container_name: jenkins-master
    build:
      context: ./
      dockerfile: jenkins-master/Dockerfile
    ports:
      - "8080:8080"  # Jenkins web UI
      - "50000:50000" # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistent storage for Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to use Docker
    restart: always
    env_file:
      - ./environment/.env

  jenkins-agent:
    image: jenkins/inbound-agent
    container_name: jenkins-agent
    env_file:
      - ./environment/.env
    depends_on:
      - jenkins-master
    restart: always

volumes:
  jenkins_home: